name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true

      - name: Run tests
        run: make test

      - name: Build binaries
        run: make build-all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lazybucket-darwin-amd64
            lazybucket-darwin-arm64
            lazybucket-linux-amd64
            lazybucket-windows-amd64.exe
          generate_release_notes: true
